# Generated by Django 3.2.12 on 2024-02-02 18:02

from django.db import migrations, models
import django.db.models.deletion
import fashion.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(blank=True, default=fashion.models.Client.get_client_id, max_length=30)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=10)),
                ('full_name', models.CharField(max_length=30)),
                ('home_address', models.CharField(blank=True, max_length=30, null=True)),
                ('office_address', models.CharField(blank=True, max_length=30, null=True)),
                ('phone_number', models.CharField(max_length=30)),
                ('whatsapp_number', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('passport', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Outfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sleeve_length', models.IntegerField(blank=True, null=True)),
                ('round_sleeve', models.IntegerField(blank=True, null=True)),
                ('chest_width', models.IntegerField(blank=True, null=True)),
                ('neck_circumference', models.IntegerField(blank=True, null=True)),
                ('shoulder_length', models.IntegerField(blank=True, null=True)),
                ('abdomen_circumference', models.IntegerField(blank=True, null=True)),
                ('arm_muscle_circumference', models.IntegerField(blank=True, null=True)),
                ('trouser_length', models.IntegerField(blank=True, null=True)),
                ('laps_circumference', models.IntegerField(blank=True, null=True)),
                ('knee_circumference', models.IntegerField(blank=True, null=True)),
                ('shoulder_to_knee_length', models.IntegerField(blank=True, null=True)),
                ('waist_circumference', models.IntegerField(blank=True, null=True)),
                ('ankle_circumference', models.IntegerField(blank=True, null=True)),
                ('kaftan_length', models.IntegerField(blank=True, null=True)),
                ('senator_length', models.IntegerField(blank=True, null=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='outfit', to='fashion.client')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OutfitStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('order created', 'order_created'), ('measurement acquired', 'measurement_acquired'), ('advance payment made', 'advanced_payment_made'), ('sewing commenced', 'sewing_commenced'), ('ready for delivery', 'ready_for_delivery'), ('payment completed', 'payment_completed'), ('delivered', 'delivered')], max_length=20)),
                ('date', models.DateTimeField()),
                ('outfit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_log', to='fashion.outfit')),
            ],
        ),
        migrations.CreateModel(
            name='ClientBodyMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sleeve_length', models.IntegerField(blank=True, null=True)),
                ('round_sleeve', models.IntegerField(blank=True, null=True)),
                ('chest_width', models.IntegerField(blank=True, null=True)),
                ('neck_circumference', models.IntegerField(blank=True, null=True)),
                ('shoulder_length', models.IntegerField(blank=True, null=True)),
                ('abdomen_circumference', models.IntegerField(blank=True, null=True)),
                ('arm_muscle_circumference', models.IntegerField(blank=True, null=True)),
                ('trouser_length', models.IntegerField(blank=True, null=True)),
                ('laps_circumference', models.IntegerField(blank=True, null=True)),
                ('knee_circumference', models.IntegerField(blank=True, null=True)),
                ('shoulder_to_knee_length', models.IntegerField(blank=True, null=True)),
                ('waist_circumference', models.IntegerField(blank=True, null=True)),
                ('ankle_circumference', models.IntegerField(blank=True, null=True)),
                ('kaftan_length', models.IntegerField(blank=True, null=True)),
                ('senator_length', models.IntegerField(blank=True, null=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='measurement', to='fashion.client')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
