# Generated by Django 3.2.12 on 2024-02-10 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fashion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='OutfitOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sleeve_length', models.IntegerField(blank=True, null=True)),
                ('round_sleeve', models.IntegerField(blank=True, null=True)),
                ('chest_width', models.IntegerField(blank=True, null=True)),
                ('neck_circumference', models.IntegerField(blank=True, null=True)),
                ('shoulder_length', models.IntegerField(blank=True, null=True)),
                ('abdomen_circumference', models.IntegerField(blank=True, null=True)),
                ('arm_muscle_circumference', models.IntegerField(blank=True, null=True)),
                ('trouser_length', models.IntegerField(blank=True, null=True)),
                ('laps_circumference', models.IntegerField(blank=True, null=True)),
                ('knee_circumference', models.IntegerField(blank=True, null=True)),
                ('shoulder_to_knee_length', models.IntegerField(blank=True, null=True)),
                ('waist_circumference', models.IntegerField(blank=True, null=True)),
                ('ankle_circumference', models.IntegerField(blank=True, null=True)),
                ('kaftan_length', models.IntegerField(blank=True, null=True)),
                ('senator_length', models.IntegerField(blank=True, null=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='outfit', to='fashion.client')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OutfitOrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sleeve_length', models.IntegerField(blank=True, null=True)),
                ('round_sleeve', models.IntegerField(blank=True, null=True)),
                ('chest_width', models.IntegerField(blank=True, null=True)),
                ('neck_circumference', models.IntegerField(blank=True, null=True)),
                ('shoulder_length', models.IntegerField(blank=True, null=True)),
                ('abdomen_circumference', models.IntegerField(blank=True, null=True)),
                ('arm_muscle_circumference', models.IntegerField(blank=True, null=True)),
                ('trouser_length', models.IntegerField(blank=True, null=True)),
                ('laps_circumference', models.IntegerField(blank=True, null=True)),
                ('knee_circumference', models.IntegerField(blank=True, null=True)),
                ('shoulder_to_knee_length', models.IntegerField(blank=True, null=True)),
                ('waist_circumference', models.IntegerField(blank=True, null=True)),
                ('ankle_circumference', models.IntegerField(blank=True, null=True)),
                ('kaftan_length', models.IntegerField(blank=True, null=True)),
                ('senator_length', models.IntegerField(blank=True, null=True)),
                ('labour_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('material_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('extra_design_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('designer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='oufit_order', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_details', to='fashion.outfitorder')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outfit_order_style', to='fashion.catalogue')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OutfitOrderStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('order created', 'order created - wating for measurements.'), ('measurement acquired', 'measurement acquired - waiting for a advance on payment.'), ('advance payment made', 'advanced payment made - advance payment has been confirmed, awaiting order processing.'), ('sewing commenced', 'sewing commenced - order is been processed.'), ('ready for delivery', 'ready for delivery - order is ready for delivery.'), ('payment completed', 'payment completed - order payment has been completed.'), ('delivered', 'delivered - this order has been delivered.')], max_length=20)),
                ('date', models.DateTimeField()),
                ('outfit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_log', to='fashion.outfitorder')),
            ],
        ),
        migrations.RemoveField(
            model_name='outfitstatuslog',
            name='outfit',
        ),
        migrations.DeleteModel(
            name='Outfit',
        ),
        migrations.DeleteModel(
            name='OutfitStatusLog',
        ),
        migrations.AddField(
            model_name='outfitorder',
            name='style',
            field=models.ManyToManyField(through='fashion.OutfitOrderDetails', to='fashion.Catalogue'),
        ),
    ]
