# Generated by Django 4.2.15 on 2024-09-02 17:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import fashion.models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0002_auto_20240210_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientbodymeasurement',
            name='shoulder_to_knee_length',
        ),
        migrations.RemoveField(
            model_name='outfitorder',
            name='shoulder_to_knee_length',
        ),
        migrations.RemoveField(
            model_name='outfitorderdetails',
            name='shoulder_to_knee_length',
        ),
        migrations.AddField(
            model_name='client',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientbodymeasurement',
            name='agbada_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientbodymeasurement',
            name='armhole_circumference',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientbodymeasurement',
            name='back_width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientbodymeasurement',
            name='buba_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientbodymeasurement',
            name='bust_circumference',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientbodymeasurement',
            name='bust_to_waist_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientbodymeasurement',
            name='calf_circumference',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientbodymeasurement',
            name='crotch_depth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientbodymeasurement',
            name='dress_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientbodymeasurement',
            name='hip_circumference',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientbodymeasurement',
            name='iro_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientbodymeasurement',
            name='jacket_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientbodymeasurement',
            name='jacket_sleeve_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientbodymeasurement',
            name='neck_to_knee_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientbodymeasurement',
            name='rise_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientbodymeasurement',
            name='shoulder_to_floor_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientbodymeasurement',
            name='shoulder_to_hip_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientbodymeasurement',
            name='shoulder_to_waist_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientbodymeasurement',
            name='skirt_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientbodymeasurement',
            name='thigh_circumference',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientbodymeasurement',
            name='waist_to_hip_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientbodymeasurement',
            name='waistcoat_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientbodymeasurement',
            name='wrist_circumference',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outfitorder',
            name='agbada_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outfitorder',
            name='armhole_circumference',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outfitorder',
            name='back_width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outfitorder',
            name='buba_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outfitorder',
            name='bust_circumference',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outfitorder',
            name='bust_to_waist_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outfitorder',
            name='calf_circumference',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outfitorder',
            name='crotch_depth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outfitorder',
            name='dress_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outfitorder',
            name='hip_circumference',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outfitorder',
            name='iro_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outfitorder',
            name='jacket_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outfitorder',
            name='jacket_sleeve_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outfitorder',
            name='neck_to_knee_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outfitorder',
            name='rise_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outfitorder',
            name='shoulder_to_floor_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outfitorder',
            name='shoulder_to_hip_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outfitorder',
            name='shoulder_to_waist_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outfitorder',
            name='skirt_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outfitorder',
            name='thigh_circumference',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outfitorder',
            name='waist_to_hip_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outfitorder',
            name='waistcoat_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outfitorder',
            name='wrist_circumference',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outfitorderdetails',
            name='agbada_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outfitorderdetails',
            name='armhole_circumference',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outfitorderdetails',
            name='back_width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outfitorderdetails',
            name='buba_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outfitorderdetails',
            name='bust_circumference',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outfitorderdetails',
            name='bust_to_waist_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outfitorderdetails',
            name='calf_circumference',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outfitorderdetails',
            name='crotch_depth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outfitorderdetails',
            name='dress_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outfitorderdetails',
            name='hip_circumference',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outfitorderdetails',
            name='iro_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outfitorderdetails',
            name='jacket_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outfitorderdetails',
            name='jacket_sleeve_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outfitorderdetails',
            name='neck_to_knee_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outfitorderdetails',
            name='rise_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outfitorderdetails',
            name='shoulder_to_floor_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outfitorderdetails',
            name='shoulder_to_hip_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outfitorderdetails',
            name='shoulder_to_waist_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outfitorderdetails',
            name='skirt_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outfitorderdetails',
            name='thigh_circumference',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outfitorderdetails',
            name='waist_to_hip_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outfitorderdetails',
            name='waistcoat_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outfitorderdetails',
            name='wrist_circumference',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_id',
            field=models.CharField(blank=True, default=fashion.models.Client.get_client_id, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='home_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='office_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='passport',
            field=models.ImageField(blank=True, null=True, upload_to='clients/passports'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='outfitorder',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='outfit_order', to='fashion.client'),
        ),
    ]
