# Generated by Django 4.2.15 on 2024-09-02 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fashion', '0003_remove_clientbodymeasurement_shoulder_to_knee_length_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BespokeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waist_circumference', models.IntegerField(blank=True, null=True)),
                ('hip_circumference', models.IntegerField(blank=True, null=True)),
                ('bust_circumference', models.IntegerField(blank=True, null=True)),
                ('shoulder_length', models.IntegerField(blank=True, null=True)),
                ('shoulder_to_waist_length', models.IntegerField(blank=True, null=True)),
                ('shoulder_to_hip_length', models.IntegerField(blank=True, null=True)),
                ('shoulder_to_floor_length', models.IntegerField(blank=True, null=True)),
                ('chest_width', models.IntegerField(blank=True, null=True)),
                ('back_width', models.IntegerField(blank=True, null=True)),
                ('sleeve_length', models.IntegerField(blank=True, null=True)),
                ('round_sleeve', models.IntegerField(blank=True, null=True)),
                ('neck_circumference', models.IntegerField(blank=True, null=True)),
                ('abdomen_circumference', models.IntegerField(blank=True, null=True)),
                ('arm_muscle_circumference', models.IntegerField(blank=True, null=True)),
                ('trouser_length', models.IntegerField(blank=True, null=True)),
                ('laps_circumference', models.IntegerField(blank=True, null=True)),
                ('knee_circumference', models.IntegerField(blank=True, null=True)),
                ('ankle_circumference', models.IntegerField(blank=True, null=True)),
                ('crotch_depth', models.IntegerField(blank=True, null=True)),
                ('rise_length', models.IntegerField(blank=True, null=True)),
                ('jacket_length', models.IntegerField(blank=True, null=True)),
                ('jacket_sleeve_length', models.IntegerField(blank=True, null=True)),
                ('waistcoat_length', models.IntegerField(blank=True, null=True)),
                ('skirt_length', models.IntegerField(blank=True, null=True)),
                ('dress_length', models.IntegerField(blank=True, null=True)),
                ('bust_to_waist_length', models.IntegerField(blank=True, null=True)),
                ('waist_to_hip_length', models.IntegerField(blank=True, null=True)),
                ('kaftan_length', models.IntegerField(blank=True, null=True)),
                ('senator_length', models.IntegerField(blank=True, null=True)),
                ('agbada_length', models.IntegerField(blank=True, null=True)),
                ('buba_length', models.IntegerField(blank=True, null=True)),
                ('iro_length', models.IntegerField(blank=True, null=True)),
                ('calf_circumference', models.IntegerField(blank=True, null=True)),
                ('thigh_circumference', models.IntegerField(blank=True, null=True)),
                ('armhole_circumference', models.IntegerField(blank=True, null=True)),
                ('wrist_circumference', models.IntegerField(blank=True, null=True)),
                ('neck_to_knee_length', models.IntegerField(blank=True, null=True)),
                ('labour_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('material_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('extra_design_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bespoke_order', to='fashion.client')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BespokeOrderStaffInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delegation', models.CharField(choices=[('tailor', 'tailor'), ('beader', 'beader'), ('stoner', 'stoner')], default='tailor', max_length=20)),
                ('pay', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('status', models.CharField(choices=[('accepted', 'accepted'), ('completed', 'completed'), ('approved', 'approved')], max_length=20)),
                ('date_accepted', models.DateTimeField(blank=True, null=True)),
                ('date_completed', models.DateTimeField(blank=True, null=True)),
                ('date_approved', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_info', to='fashion.bespokeorder')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bespoke_order_staff_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='outfitorderdetails',
            name='designer',
        ),
        migrations.RemoveField(
            model_name='outfitorderdetails',
            name='order',
        ),
        migrations.RemoveField(
            model_name='outfitorderdetails',
            name='style',
        ),
        migrations.RenameModel(
            old_name='OutfitOrderStatusLog',
            new_name='BespokeOrderStatusLog',
        ),
        migrations.DeleteModel(
            name='OutfitOrder',
        ),
        migrations.DeleteModel(
            name='OutfitOrderDetails',
        ),
        migrations.AddField(
            model_name='bespokeorder',
            name='staff',
            field=models.ManyToManyField(related_name='bespoke_order', through='fashion.BespokeOrderStaffInfo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bespokeorder',
            name='style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bespoke_order', to='fashion.catalogue'),
        ),
        migrations.AlterField(
            model_name='bespokeorderstatuslog',
            name='outfit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_log', to='fashion.bespokeorder'),
        ),
    ]
