# Generated by Django 4.2.15 on 2024-09-13 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0004_bespokeorder_bespokeorderstaffinfo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bespokeorderstaffinfo',
            name='delegation',
            field=models.CharField(choices=[('tailor', 'tailor'), ('beader', 'beader'), ('stoner', 'stoner'), ('embelishment', 'embelishment')], default='tailor', max_length=20),
        ),
    ]
