# Generated by Django 4.2.15 on 2024-09-13 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0005_alter_bespokeorderstaffinfo_delegation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bespokeorder',
            name='abdomen_circumference',
        ),
        migrations.RemoveField(
            model_name='bespokeorder',
            name='ankle_circumference',
        ),
        migrations.RemoveField(
            model_name='bespokeorder',
            name='arm_muscle_circumference',
        ),
        migrations.RemoveField(
            model_name='bespokeorder',
            name='back_width',
        ),
        migrations.RemoveField(
            model_name='bespokeorder',
            name='bust_to_waist_length',
        ),
        migrations.RemoveField(
            model_name='bespokeorder',
            name='chest_width',
        ),
        migrations.RemoveField(
            model_name='bespokeorder',
            name='crotch_depth',
        ),
        migrations.RemoveField(
            model_name='bespokeorder',
            name='dress_length',
        ),
        migrations.RemoveField(
            model_name='bespokeorder',
            name='laps_circumference',
        ),
        migrations.RemoveField(
            model_name='bespokeorder',
            name='neck_to_knee_length',
        ),
        migrations.RemoveField(
            model_name='bespokeorder',
            name='rise_length',
        ),
        migrations.RemoveField(
            model_name='bespokeorder',
            name='round_sleeve',
        ),
        migrations.RemoveField(
            model_name='bespokeorder',
            name='shoulder_to_floor_length',
        ),
        migrations.RemoveField(
            model_name='bespokeorder',
            name='shoulder_to_hip_length',
        ),
        migrations.RemoveField(
            model_name='bespokeorder',
            name='shoulder_to_waist_length',
        ),
        migrations.RemoveField(
            model_name='bespokeorder',
            name='skirt_length',
        ),
        migrations.RemoveField(
            model_name='bespokeorder',
            name='thigh_circumference',
        ),
        migrations.RemoveField(
            model_name='bespokeorder',
            name='waist_to_hip_length',
        ),
        migrations.RemoveField(
            model_name='bespokeorder',
            name='wrist_circumference',
        ),
        migrations.RemoveField(
            model_name='clientbodymeasurement',
            name='abdomen_circumference',
        ),
        migrations.RemoveField(
            model_name='clientbodymeasurement',
            name='ankle_circumference',
        ),
        migrations.RemoveField(
            model_name='clientbodymeasurement',
            name='arm_muscle_circumference',
        ),
        migrations.RemoveField(
            model_name='clientbodymeasurement',
            name='back_width',
        ),
        migrations.RemoveField(
            model_name='clientbodymeasurement',
            name='bust_to_waist_length',
        ),
        migrations.RemoveField(
            model_name='clientbodymeasurement',
            name='chest_width',
        ),
        migrations.RemoveField(
            model_name='clientbodymeasurement',
            name='crotch_depth',
        ),
        migrations.RemoveField(
            model_name='clientbodymeasurement',
            name='dress_length',
        ),
        migrations.RemoveField(
            model_name='clientbodymeasurement',
            name='laps_circumference',
        ),
        migrations.RemoveField(
            model_name='clientbodymeasurement',
            name='neck_to_knee_length',
        ),
        migrations.RemoveField(
            model_name='clientbodymeasurement',
            name='rise_length',
        ),
        migrations.RemoveField(
            model_name='clientbodymeasurement',
            name='round_sleeve',
        ),
        migrations.RemoveField(
            model_name='clientbodymeasurement',
            name='shoulder_to_floor_length',
        ),
        migrations.RemoveField(
            model_name='clientbodymeasurement',
            name='shoulder_to_hip_length',
        ),
        migrations.RemoveField(
            model_name='clientbodymeasurement',
            name='shoulder_to_waist_length',
        ),
        migrations.RemoveField(
            model_name='clientbodymeasurement',
            name='skirt_length',
        ),
        migrations.RemoveField(
            model_name='clientbodymeasurement',
            name='thigh_circumference',
        ),
        migrations.RemoveField(
            model_name='clientbodymeasurement',
            name='waist_to_hip_length',
        ),
        migrations.RemoveField(
            model_name='clientbodymeasurement',
            name='wrist_circumference',
        ),
        migrations.AddField(
            model_name='bespokeorder',
            name='back_depth',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='bespokeorder',
            name='blouse_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='bespokeorder',
            name='bottom_circumference',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='bespokeorder',
            name='bust_point',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='bespokeorder',
            name='chest_circumference',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='bespokeorder',
            name='lap_circumference',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='bespokeorder',
            name='long_gown_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='bespokeorder',
            name='long_skirt_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='bespokeorder',
            name='nipple_point_2_point_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='bespokeorder',
            name='round_sleeves_circumference',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='bespokeorder',
            name='round_underbust',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='bespokeorder',
            name='short_gown_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='bespokeorder',
            name='short_skirt_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='bespokeorder',
            name='shoulder_to_halflength',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='bespokeorder',
            name='shoulder_to_hip',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='bespokeorder',
            name='shoulder_to_knee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='bespokeorder',
            name='shoulder_to_underbust',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='bespokeorder',
            name='skirt_waist_circumference',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='bespokeorder',
            name='top_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='bespokeorder',
            name='trouser_waist_circumference',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='clientbodymeasurement',
            name='back_depth',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='clientbodymeasurement',
            name='blouse_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='clientbodymeasurement',
            name='bottom_circumference',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='clientbodymeasurement',
            name='bust_point',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='clientbodymeasurement',
            name='chest_circumference',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='clientbodymeasurement',
            name='lap_circumference',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='clientbodymeasurement',
            name='long_gown_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='clientbodymeasurement',
            name='long_skirt_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='clientbodymeasurement',
            name='nipple_point_2_point_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='clientbodymeasurement',
            name='round_sleeves_circumference',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='clientbodymeasurement',
            name='round_underbust',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='clientbodymeasurement',
            name='short_gown_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='clientbodymeasurement',
            name='short_skirt_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='clientbodymeasurement',
            name='shoulder_to_halflength',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='clientbodymeasurement',
            name='shoulder_to_hip',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='clientbodymeasurement',
            name='shoulder_to_knee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='clientbodymeasurement',
            name='shoulder_to_underbust',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='clientbodymeasurement',
            name='skirt_waist_circumference',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='clientbodymeasurement',
            name='top_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='clientbodymeasurement',
            name='trouser_waist_circumference',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='bespokeorder',
            name='agbada_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='bespokeorder',
            name='armhole_circumference',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='bespokeorder',
            name='buba_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='bespokeorder',
            name='bust_circumference',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='bespokeorder',
            name='calf_circumference',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='bespokeorder',
            name='hip_circumference',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='bespokeorder',
            name='iro_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='bespokeorder',
            name='jacket_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='bespokeorder',
            name='jacket_sleeve_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='bespokeorder',
            name='kaftan_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='bespokeorder',
            name='knee_circumference',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='bespokeorder',
            name='neck_circumference',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='bespokeorder',
            name='senator_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='bespokeorder',
            name='shoulder_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='bespokeorder',
            name='sleeve_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='bespokeorder',
            name='trouser_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='bespokeorder',
            name='waist_circumference',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='bespokeorder',
            name='waistcoat_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='clientbodymeasurement',
            name='agbada_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='clientbodymeasurement',
            name='armhole_circumference',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='clientbodymeasurement',
            name='buba_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='clientbodymeasurement',
            name='bust_circumference',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='clientbodymeasurement',
            name='calf_circumference',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='clientbodymeasurement',
            name='hip_circumference',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='clientbodymeasurement',
            name='iro_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='clientbodymeasurement',
            name='jacket_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='clientbodymeasurement',
            name='jacket_sleeve_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='clientbodymeasurement',
            name='kaftan_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='clientbodymeasurement',
            name='knee_circumference',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='clientbodymeasurement',
            name='neck_circumference',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='clientbodymeasurement',
            name='senator_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='clientbodymeasurement',
            name='shoulder_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='clientbodymeasurement',
            name='sleeve_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='clientbodymeasurement',
            name='trouser_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='clientbodymeasurement',
            name='waist_circumference',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='clientbodymeasurement',
            name='waistcoat_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
