# Generated by Django 4.2.15 on 2024-09-28 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0006_alter_staffrole_name'),
        ('fashion', '0008_alter_bespokeorder_agbada_length_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bespokeorder',
            name='staff',
            field=models.ManyToManyField(related_name='bespoke_order', through='fashion.BespokeOrderStaffInfo', to='myadmin.staff'),
        ),
        migrations.AlterField(
            model_name='bespokeorderstaffinfo',
            name='delegation',
            field=models.CharField(choices=[('tailor', 'tailor'), ('beader', 'beader'), ('stoner', 'stoner'), ('embellishment', 'embellishment')], default='tailor', max_length=20),
        ),
        migrations.AlterField(
            model_name='bespokeorderstaffinfo',
            name='pay',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bespokeorderstaffinfo',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bespoke_order_staff_info', to='myadmin.staff'),
        ),
        migrations.AlterField(
            model_name='bespokeorderstaffinfo',
            name='status',
            field=models.CharField(choices=[('accepted', 'accepted'), ('completed', 'completed'), ('approved', 'approved')], default='accepted', max_length=20),
        ),
    ]
