# Generated by Django 4.2.15 on 2024-09-28 14:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0009_alter_bespokeorder_staff_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogue',
            options={'ordering': ['title'], 'verbose_name': 'Catalogue Item', 'verbose_name_plural': 'Catalogue Items'},
        ),
        migrations.AddField(
            model_name='catalogue',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='catalogue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 9, 28, 14, 25, 42, 678782, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='catalogue',
            name='description_text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='catalogue',
            name='title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='catalogue',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='CatalogueImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='catalogue_images/')),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True)),
                ('catalogue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='fashion.catalogue')),
            ],
            options={
                'verbose_name': 'Catalogue Image',
                'verbose_name_plural': 'Catalogue Images',
            },
        ),
    ]
