# Generated by Django 4.2.15 on 2024-11-07 10:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0010_alter_catalogue_options_catalogue_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bespokeorder',
            name='expected_date_of_delivery',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bespokeorder',
            name='style',
            field=models.ForeignKey(blank=True, help_text='You can leave style blank', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bespoke_order', to='fashion.catalogue'),
        ),
    ]
