# Generated by Django 4.2.15 on 2024-11-08 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0011_bespokeorder_expected_date_of_delivery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bespokeorder',
            name='order_id',
            field=models.CharField(max_length=8, null=True, unique=True),
        ),
    ]
