# Generated by Django 4.2.15 on 2024-11-08 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0013_alter_bespokeorder_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bespokeorderstatuslog',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
