# Generated by Django 4.2.15 on 2024-11-08 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0014_alter_bespokeorderstatuslog_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bespokeorderstatuslog',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
