# Generated by Django 4.2.15 on 2024-11-13 13:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0015_bespokeorderstatuslog_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='bespokeorderstaffinfo',
            name='date_assigned',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bespokeorderstaffinfo',
            name='status',
            field=models.CharField(choices=[('assigned', 'assigned'), ('accepted', 'accepted'), ('completed', 'completed'), ('approved', 'approved')], default='assigned', max_length=20),
        ),
    ]
