# Generated by Django 4.2.15 on 2024-11-14 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0016_bespokeorderstaffinfo_date_assigned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bespokeorderstaffinfo',
            name='date_staff_is_paid',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bespokeorderstaffinfo',
            name='status',
            field=models.CharField(choices=[('assigned', 'assigned'), ('accepted', 'accepted'), ('completed', 'completed'), ('approved', 'approved'), ('paid', 'paid')], default='assigned', max_length=20),
        ),
    ]
