# Generated by Django 4.2.15 on 2024-11-19 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0018_bespokeorder_advance_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='bespokeorder',
            name='last_status_log',
            field=models.CharField(default='created', max_length=30),
            preserve_default=False,
        ),
    ]
