# Generated by Django 4.2.15 on 2024-11-19 06:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0019_bespokeorder_last_status_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='bespokeorder',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
