# Generated by Django 4.2.15 on 2024-11-28 06:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import fashion.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_productcategory_gender'),
        ('fashion', '0020_bespokeorder_date_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogueimage',
            options={'ordering': ['position'], 'verbose_name': 'Catalogue Image', 'verbose_name_plural': 'Catalogue Images'},
        ),
        migrations.AddField(
            model_name='catalogue',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalogue', to='shop.productcategory'),
        ),
        migrations.AddField(
            model_name='catalogue',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional discounted price for the item.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='catalogue',
            name='slug',
            field=models.SlugField(blank=True, help_text='Unique URL-friendly identifier for the catalogue item.', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='catalogueimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='catalogueimage',
            name='position',
            field=models.PositiveIntegerField(default=0, help_text='Position of the image in the display order.'),
        ),
        migrations.AddField(
            model_name='catalogueimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='cost',
            field=models.DecimalField(decimal_places=2, help_text='Base cost of the item in your currency.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the item was created.'),
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='description_text',
            field=models.TextField(help_text='Detailed description of the item.'),
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='title',
            field=models.CharField(help_text='Title of the catalogue item.', max_length=255),
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the item was last updated.'),
        ),
        migrations.AlterField(
            model_name='catalogueimage',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Alternative text for the image, used for accessibility.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='catalogueimage',
            name='image',
            field=models.ImageField(upload_to='catalogue_images/', validators=[fashion.models.validate_image]),
        ),
        migrations.AddIndex(
            model_name='catalogue',
            index=models.Index(fields=['title'], name='fashion_cat_title_d184be_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogue',
            index=models.Index(fields=['cost'], name='fashion_cat_cost_cea850_idx'),
        ),
    ]
