# Generated by Django 4.2.15 on 2024-12-19 17:08

from django.db import migrations, models
import fashion.models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0022_alter_bespokeorder_agbada_length_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bespokeorder',
            name='order_id',
            field=models.CharField(blank=True, default=fashion.models.BespokeOrder.get_order_id, max_length=10, unique=True),
        ),
    ]
