# Generated by Django 4.2.18 on 2025-02-05 15:18

from django.db import migrations, models
import fashion.models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0023_alter_bespokeorder_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='bespokeorder',
            name='order_id',
            field=models.CharField(blank=True, default=fashion.models.BespokeOrder.get_order_id, editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='bespokeorderstatuslog',
            name='status',
            field=models.CharField(choices=[('order created', 'order created - wating for measurements.'), ('measurement acquired', 'measurement acquired - waiting for a advance on payment.'), ('advance payment made', 'advanced payment made - advance payment has been confirmed, awaiting order processing.'), ('sewing commenced', 'sewing commenced - order is been processed.'), ('ready for delivery', 'ready for delivery - order is ready for delivery.'), ('payment completed', 'payment completed - order payment has been completed.'), ('delivered', 'delivered - this order has been delivered.'), ('cancelled', 'cancelled - this order has been cancelled.')], max_length=20),
        ),
    ]
