# Generated by Django 4.2.18 on 2025-02-05 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0025_alter_client_options_alter_client_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
