# Generated by Django 4.0.4 on 2023-08-04 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='language',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.language'),
        ),
    ]
