# Generated by Django 4.0.4 on 2023-08-22 14:17

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_notificationcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='image',
            field=models.FileField(default='', upload_to=users.models.Notification.get_image_upload_path),
            preserve_default=False,
        ),
    ]
