# Generated by Django 4.2.15 on 2024-09-14 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('staff', 'staff'), ('manager', 'manager'), ('customer', 'customer')], default='customer', max_length=30),
        ),
    ]
