# Generated by Django 4.2.15 on 2024-09-28 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_account_id_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('staff', 'staff'), ('manager', 'manager'), ('customer', 'customer')], default='customer', max_length=30, null=True),
        ),
    ]
