# Generated by Django 4.2.15 on 2024-11-20 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='access_level',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
