# Generated by Django 4.2.15 on 2024-11-28 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_custompermission_delete_savings'),
    ]

    operations = [
        migrations.AddField(
            model_name='custompermission',
            name='code',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
