# Generated by Django 4.2.15 on 2024-12-10 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_custompermission_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custompermission',
            name='name',
            field=models.CharField(choices=[('can view company financials', 'can view company financials'), ('can view customer personal info', 'can view customer personal info'), ('can modify bespoke order and related details', 'can modify bespoke order and related details'), ('can view other staffs details', 'can view other staffs details'), ('can view bespoke order status logs', 'can view bespoke order status logs')], max_length=100, unique=True),
        ),
    ]
