# Generated by Django 3.2.12 on 2023-10-20 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('NGN', 'NGN'), ('USD', 'USD'), ('GBP', 'GBP'), ('CAD', 'CAD')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyConvert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multiply_by', models.DecimalField(decimal_places=2, max_digits=100)),
                ('_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_currency', to='core.currency')),
                ('_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_currency', to='core.currency')),
            ],
        ),
    ]
