# Generated by Django 3.2.12 on 2023-10-21 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyconvert',
            name='multiply_by',
            field=models.DecimalField(decimal_places=5, max_digits=100),
        ),
    ]
