# Generated by Django 3.2.12 on 2023-10-09 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_available_on_preorder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_free_delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_ready_to_ship',
            field=models.BooleanField(default=False),
        ),
    ]
