# Generated by Django 3.2.12 on 2023-10-19 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20231009_0821'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattributeoption',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to='option_images'),
        ),
    ]
