# Generated by Django 3.2.12 on 2023-10-20 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('shop', '0005_productattributeoption_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.ForeignKey( null=True, on_delete=django.db.models.deletion.PROTECT, to='core.currency'),
            preserve_default=False,
        ),
    ]
