# Generated by Django 3.2.12 on 2023-10-21 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_product_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_available_on_preorder',
        ),
    ]
