# Generated by Django 3.2.12 on 2023-12-26 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_remove_product_is_available_on_preorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='is_collection',
            field=models.BooleanField(default=False),
        ),
    ]
