# Generated by Django 3.2.12 on 2024-08-03 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_productcategory_is_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available_units',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
