# Generated by Django 3.2.12 on 2024-08-06 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0010_productreview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='is_collection',
        ),
        migrations.AlterField(
            model_name='productreview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProductSalePromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('FIXED', 'Fixed Amount')], max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='promotion_banners/')),
                ('products', models.ManyToManyField(related_name='promotions', to='shop.Product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('banner_image', models.ImageField(upload_to='collection_banners/')),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('products', models.ManyToManyField(related_name='collections', to='shop.Product')),
            ],
        ),
    ]
