# Generated by Django 3.2.12 on 2024-08-08 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20240806_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='gender',
            field=models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Unisex', 'Unisex')], default='Unisex', max_length=10),
        ),
    ]
