# Generated by Django 4.2.15 on 2024-09-14 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='position',
        ),
        migrations.AlterField(
            model_name='staff',
            name='national_id_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
