# Generated by Django 4.2.15 on 2024-09-19 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0002_remove_staff_position_alter_staff_national_id_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='bank_name',
            field=models.CharField(blank=True, help_text='e.g UBA', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='date_terminated',
            field=models.DateTimeField(blank=True, help_text="Leave Blank if staff's contract is not being terminated", null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='is_salary_fixed',
            field=models.BooleanField(default=True, verbose_name='Is This Staff Salary fixed ?'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='national_id_number',
            field=models.CharField(blank=True, help_text='NIN, for identification', max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='If the salary is not fixed, you can skip this', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='salary_cycle',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly')], default='weekly', help_text='The frequency of salary payment for this staff', max_length=20),
        ),
        migrations.CreateModel(
            name='StaffTransactionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('savings', 'Savings'), ('withdrawal', 'Withdrawal')], max_length=20)),
                ('date_initiated', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('status', models.CharField(choices=[('created', 'Created'), ('confirmed', 'Confirmed')], default='created', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_logs', to='myadmin.staff')),
            ],
            options={
                'ordering': ['-date_initiated'],
            },
        ),
    ]
