# Generated by Django 4.2.15 on 2024-09-19 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0003_alter_staff_bank_name_alter_staff_date_terminated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='employee_id',
            field=models.CharField(db_index=True, default='', max_length=5),
            preserve_default=False,
        ),
    ]
