# Generated by Django 4.2.15 on 2024-11-07 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0006_alter_staffrole_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(choices=[('tailoring', 'Tailoring'), ('designing', 'Designing'), ('finishing', 'Finishing'), ('administration', 'Administration'), ('sales', 'sales'), ('security', 'Security'), ('logistics', 'Logistics'), ('customer service', 'Customer Service'), ('beading', 'Beading'), ('assistant', 'Assistant'), ('cleaning', 'Cleaning'), ('kitchen', 'Kitchen'), ('others', 'Others')], max_length=20),
        ),
    ]
