# Generated by Django 4.2.15 on 2024-11-13 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0007_alter_department_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='is_salary_fixed',
            field=models.BooleanField(default=True, help_text='uncheck if it does not apply to this staff', verbose_name='Is This Staff Salary fixed ?'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fixed salaries are for staffs whose salary is pre-dermined for their salary cycles. ', max_digits=20, null=True),
        ),
    ]
