# Generated by Django 4.2.15 on 2024-11-15 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0017_bespokeorderstaffinfo_date_staff_is_paid_and_more'),
        ('myadmin', '0008_alter_staff_is_salary_fixed_alter_staff_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffsalarylog',
            name='bespoke_orders',
            field=models.ManyToManyField(related_name='salary_log', to='fashion.bespokeorder'),
        ),
    ]
