# Generated by Django 4.2.15 on 2024-12-10 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0009_staffsalarylog_bespoke_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffsalarylog',
            name='date_due',
            field=models.DateField(auto_now_add=True),
        ),
    ]
