# Generated by Django 4.2.15 on 2024-12-12 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0010_alter_staffsalarylog_date_due'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffsalarylog',
            name='remarks',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(choices=[('tailoring', 'Tailoring'), ('designing', 'Designing'), ('finishing', 'Finishing'), ('administration', 'Administration'), ('sales', 'sales'), ('security', 'Security'), ('logistics', 'Logistics'), ('customer service', 'Customer Service'), ('beading', 'Beading'), ('stoning', 'Stoning'), ('assistant', 'Assistant'), ('cleaning', 'Cleaning'), ('kitchen', 'Kitchen'), ('others', 'Others')], max_length=20),
        ),
        migrations.AlterField(
            model_name='staffrole',
            name='name',
            field=models.CharField(choices=[('ceo', 'Ceo'), ('general manager', 'General manager'), ('recruitment manager', 'Recruitment manager'), ('safety manager', 'Safety manager'), ('design', 'Design'), ('social media manager', 'Social media manager'), ('customer service', 'Customer service'), ('technical manager', 'Technical manager'), ('maintenance manager', 'Maintenance manager'), ('quality control manager', 'Quality control manager'), ('sales repesentative', 'Sales repesentative'), ('personal assistant to ceo', 'Personal assistant to ceo'), ('head tailor', 'Head tailor'), ('head beeder', 'Head beeder'), ('head stoner', 'Head stoner'), ('eventry', 'Eventry'), ('no role', 'No role')], max_length=50),
        ),
    ]
